# Generated by Django 5.2.8 on 2025-11-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_all_cadets', 'Can view all cadets'), ('can_manage_unit', 'Can manage unit'), ('can_mark_attendance', 'Can mark attendance'), ('can_create_events', 'Can create events'))},
        ),
    ]
